import fs from "fs";
import path from "path";
import {
  inferLanguageFromState,
  languageCode,
} from "./language";
import { isValidationHistoryEntry } from "./validationCommands";
import type {
  DeliveryDocsOptions,
  DeliveryDocsResult,
  PipelineStateLike,
} from "./types";

interface DeliveryDocText {
  noData: string;
  noApi: string;
  noArch: string;
  noImpl: string;
  noChange: string;
  noTrace: string;
  noValidation: string;
  traceNotice: string;
  generated: string;
}

/**
 * @param {unknown} value
 * @returns {unknown[]}
 */
function normalizeArray(value: unknown): unknown[] {
  if (!value) {
    return [];
  }
  return Array.isArray(value) ? value : [value];
}

/**
 * @param {unknown} item
 * @returns {string}
 */
function stringifyItem(item: unknown): string {
  if (item === null || item === undefined) {
    return "";
  }
  if (typeof item === "string") {
    return item;
  }
  if (typeof item === "object") {
    return Object.entries(item)
      .map(([key, value]) => `${key}: ${Array.isArray(value) ? value.join(", ") : value}`)
      .join("; ");
  }
  return String(item);
}

/**
 * @param {import("./types").PipelineStateLike} state
 * @returns {unknown[]}
 */
function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {};
}

function traceabilityIterations(state: PipelineStateLike): unknown[] {
  const traceability = state.traceability && typeof state.traceability === "object"
    ? state.traceability as { iterations?: unknown }
    : {};
  return normalizeArray(traceability.iterations);
}

/**
 * @param {unknown} items
 * @param {string} fallback
 * @returns {string}
 */
function bulletList(items: unknown, fallback: string): string {
  const lines = normalizeArray(items)
    .map(stringifyItem)
    .map((item) => item.trim())
    .filter(Boolean);
  if (lines.length === 0) {
    return `- ${fallback}`;
  }
  return lines.map((item) => `- ${item}`).join("\n");
}

/**
 * @param {import("./types").PipelineStateLike} state
 * @param {string} fallback
 * @returns {string}
 */
function commandList(state: PipelineStateLike, fallback: string): string {
  const commands = normalizeArray(state.validation && state.validation.commands)
    .map((item) => {
      if (typeof item === "string") {
        return item;
      }
      if (item && typeof item === "object") {
        const commandItem = item as { command?: unknown };
        if (!isValidationHistoryEntry(item)) {
          return typeof commandItem.command === "string" ? commandItem.command : "";
        }
        return `${item.command || "not_run"} -> ${item.result || item.status || "unknown"}${item.summary ? ` (${item.summary})` : ""}`;
      }
      return "";
    })
    .filter(Boolean);
  return bulletList(commands, fallback);
}

/**
 * @param {import("./types").PipelineStateLike} state
 * @param {string} fallback
 * @returns {string}
 */
function traceLines(state: PipelineStateLike, fallback: string): string {
  const iterations = traceabilityIterations(state);
  if (iterations.length === 0) {
    return `- ${fallback}`;
  }
  return iterations.map((rawItem) => {
    const item = asRecord(rawItem);
    const focus = asRecord(item.focus);
    const focusText = focus.type
      ? `${focus.type}${focus.reqId ? `:${focus.reqId}` : ""}`
      : "unknown";
    return `- Iteration ${item.iteration || "?"} (${focusText}): ${item.rationaleSummary || item.summary || fallback}`;
  }).join("\n");
}

/**
 * @param {unknown} language
 * @returns {Record<string, string>}
 */
function docText(language: unknown): DeliveryDocText {
  if (languageCode(language) === "en") {
    return {
      noData: "No explicit record",
      noApi: "No API changes were reported",
      noArch: "No architecture notes were reported",
      noImpl: "No implementation notes were reported",
      noChange: "No changelog entries were reported",
      noTrace: "No traceability iteration has been recorded",
      noValidation: "No validation command has been recorded",
      traceNotice: "This document records public audit summaries only. It must not contain private chain-of-thought.",
      generated: "Generated by `fastcar-cli auto-iterate --finalize`.",
    };
  }
  return {
    noData: "未记录",
    noApi: "未报告 API 变化",
    noArch: "未报告架构说明",
    noImpl: "未报告实现说明",
    noChange: "未报告变更记录",
    noTrace: "尚未记录可追溯迭代",
    noValidation: "尚未记录验证命令",
    traceNotice: "本文档只记录公开可审计推理摘要，不记录私有思考链。",
    generated: "由 `fastcar-cli auto-iterate --finalize` 生成。",
  };
}

/**
 * @param {import("./types").PipelineStateLike} state
 * @returns {Record<string, string>}
 */
export function buildDocs(state: PipelineStateLike): Record<string, string> {
  const language = inferLanguageFromState(state);
  const text = docText(language);
  const task = asRecord(state.task);
  const delivery = state.deliveryEvidence || {};
  const documentation = asRecord(state.documentation);
  const requirements = normalizeArray(state.requirements);
  const changedFiles = normalizeArray(delivery.changedFiles).length > 0
    ? delivery.changedFiles
    : traceabilityIterations(state)
      .flatMap((item) => {
        const record = item && typeof item === "object" ? item as { filesChanged?: unknown } : {};
        return normalizeArray(record.filesChanged);
      });
  const generatedAt = new Date().toISOString();

  if (languageCode(language) === "en") {
    return {
      "api.md": [
        "# API",
        "",
        text.generated,
        "",
        "## Scope",
        task.goal || text.noData,
        "",
        "## API Changes",
        bulletList(documentation.apiChanges, text.noApi),
        "",
        "## Related Requirements",
        bulletList(requirements.map((item) => {
          const requirement = asRecord(item);
          return `${requirement.id}: ${requirement.summary} (${requirement.status})`;
        }), text.noData),
      ].join("\n"),
      "changelog.md": [
        "# Changelog",
        "",
        text.generated,
        "",
        "## Entries",
        bulletList(documentation.changelogEntries, text.noChange),
        "",
        "## Changed Files",
        bulletList(changedFiles, text.noData),
        "",
        "## Validation",
        commandList(state, text.noValidation),
      ].join("\n"),
      "architecture.md": [
        "# System Architecture",
        "",
        text.generated,
        "",
        "## Architecture Notes",
        bulletList(documentation.architectureNotes, text.noArch),
        "",
        "## Decisions",
        bulletList(traceabilityIterations(state).flatMap((item) => {
          const record = item && typeof item === "object" ? item as { decisions?: unknown } : {};
          return normalizeArray(record.decisions);
        }), text.noData),
        "",
        "## Traceability",
        text.traceNotice,
        "",
        traceLines(state, text.noTrace),
      ].join("\n"),
      "implementation.md": [
        "# Implementation Notes",
        "",
        text.generated,
        "",
        "## Core Implementation",
        bulletList(documentation.implementationNotes, text.noImpl),
        "",
        "## Delivery Evidence",
        bulletList([
          delivery.changes && `Changes: ${delivery.changes}`,
          delivery.validationSummary && `Validation: ${delivery.validationSummary}`,
          delivery.risks && `Risks: ${delivery.risks}`,
          delivery.unfinishedItems && `Unfinished: ${delivery.unfinishedItems}`,
        ].filter(Boolean), text.noData),
        "",
        "## Traceability",
        text.traceNotice,
        "",
        traceLines(state, text.noTrace),
        "",
        `Generated at: ${generatedAt}`,
      ].join("\n"),
    };
  }

  return {
    "api.md": [
      "# API 文档",
      "",
      text.generated,
      "",
      "## 范围",
      task.goal || text.noData,
      "",
      "## API 变化",
      bulletList(documentation.apiChanges, text.noApi),
      "",
      "## 关联需求",
        bulletList(requirements.map((item) => {
          const requirement = asRecord(item);
          return `${requirement.id}: ${requirement.summary} (${requirement.status})`;
        }), text.noData),
    ].join("\n"),
    "changelog.md": [
      "# 变更日志",
      "",
      text.generated,
      "",
      "## 变更项",
      bulletList(documentation.changelogEntries, text.noChange),
      "",
      "## 变更文件",
      bulletList(changedFiles, text.noData),
      "",
      "## 验证",
      commandList(state, text.noValidation),
    ].join("\n"),
    "architecture.md": [
      "# 系统架构",
      "",
      text.generated,
      "",
      "## 架构说明",
      bulletList(documentation.architectureNotes, text.noArch),
      "",
      "## 决策记录",
      bulletList(traceabilityIterations(state).flatMap((item) => {
        const record = item && typeof item === "object" ? item as { decisions?: unknown } : {};
        return normalizeArray(record.decisions);
      }), text.noData),
      "",
      "## 可追溯记录",
      text.traceNotice,
      "",
      traceLines(state, text.noTrace),
    ].join("\n"),
    "implementation.md": [
      "# 核心功能实现说明",
      "",
      text.generated,
      "",
      "## 核心实现",
      bulletList(documentation.implementationNotes, text.noImpl),
      "",
      "## 交付证据",
      bulletList([
        delivery.changes && `变更：${delivery.changes}`,
        delivery.validationSummary && `验证：${delivery.validationSummary}`,
        delivery.risks && `风险：${delivery.risks}`,
        delivery.unfinishedItems && `未完成项：${delivery.unfinishedItems}`,
      ].filter(Boolean), text.noData),
      "",
      "## 可追溯记录",
      text.traceNotice,
      "",
      traceLines(state, text.noTrace),
      "",
      `生成时间：${generatedAt}`,
    ].join("\n"),
  };
}

/**
 * @param {import("./types").DeliveryDocsOptions} options
 * @returns {Promise<import("./types").DeliveryDocsResult>}
 */
export async function generateDeliveryDocs(options: DeliveryDocsOptions): Promise<DeliveryDocsResult> {
  const state = options.state;
  const sessionDir = options.sessionDir || path.dirname(options.stateJsonPath);
  const docsDir = path.join(sessionDir, "docs");
  const docs = buildDocs(state);
  await fs.promises.mkdir(docsDir, { recursive: true });
  for (const [fileName, content] of Object.entries(docs)) {
    await fs.promises.writeFile(path.join(docsDir, fileName), `${content.trimEnd()}\n`, "utf8");
  }
  const sessionName = state.session && state.session.session ? state.session.session : "unknown";
  const files = Object.keys(docs).map((fileName) => `.agent-state/auto-iterate/${sessionName}/docs/${fileName}`);
  return {
    status: "generated",
    path: `.agent-state/auto-iterate/${sessionName}/docs`,
    files,
    generatedAt: new Date().toISOString(),
  };
}

