const fs = require("fs");
const path = require("path");
const { inferLanguageFromState, languageCode } = require("./language");

function normalizeArray(value) {
  if (!value) {
    return [];
  }
  return Array.isArray(value) ? value : [value];
}

function stringifyItem(item) {
  if (item === null || item === undefined) {
    return "";
  }
  if (typeof item === "string") {
    return item;
  }
  if (typeof item === "object") {
    return Object.entries(item)
      .map(([key, value]) => `${key}: ${Array.isArray(value) ? value.join(", ") : value}`)
      .join("; ");
  }
  return String(item);
}

function bulletList(items, fallback) {
  const lines = normalizeArray(items)
    .map(stringifyItem)
    .map((item) => item.trim())
    .filter(Boolean);
  if (lines.length === 0) {
    return `- ${fallback}`;
  }
  return lines.map((item) => `- ${item}`).join("\n");
}

function commandList(state, fallback) {
  const commands = normalizeArray(state.validation && state.validation.commands)
    .map((item) => {
      if (typeof item === "string") {
        return item;
      }
      if (item && typeof item === "object") {
        return `${item.command || "not_run"} -> ${item.result || item.status || "unknown"}${item.summary ? ` (${item.summary})` : ""}`;
      }
      return "";
    })
    .filter(Boolean);
  return bulletList(commands, fallback);
}

function traceLines(state, fallback) {
  const iterations = normalizeArray(state.traceability && state.traceability.iterations);
  if (iterations.length === 0) {
    return `- ${fallback}`;
  }
  return iterations.map((item) => {
    const focus = item.focus && item.focus.type
      ? `${item.focus.type}${item.focus.reqId ? `:${item.focus.reqId}` : ""}`
      : "unknown";
    return `- Iteration ${item.iteration || "?"} (${focus}): ${item.rationaleSummary || item.summary || fallback}`;
  }).join("\n");
}

function docText(language) {
  if (languageCode(language) === "en") {
    return {
      noData: "No explicit record",
      noApi: "No API changes were reported",
      noArch: "No architecture notes were reported",
      noImpl: "No implementation notes were reported",
      noChange: "No changelog entries were reported",
      noTrace: "No traceability iteration has been recorded",
      noValidation: "No validation command has been recorded",
      traceNotice: "This document records public audit summaries only. It must not contain private chain-of-thought.",
      generated: "Generated by `fastcar-cli auto-iterate --finalize`.",
    };
  }
  return {
    noData: "未记录",
    noApi: "未报告 API 变化",
    noArch: "未报告架构说明",
    noImpl: "未报告实现说明",
    noChange: "未报告变更记录",
    noTrace: "尚未记录可追溯迭代",
    noValidation: "尚未记录验证命令",
    traceNotice: "本文档只记录公开可审计推理摘要，不记录私有思考链。",
    generated: "由 `fastcar-cli auto-iterate --finalize` 生成。",
  };
}

function buildDocs(state) {
  const language = inferLanguageFromState(state);
  const text = docText(language);
  const task = state.task || {};
  const delivery = state.deliveryEvidence || {};
  const documentation = state.documentation || {};
  const requirements = normalizeArray(state.requirements);
  const changedFiles = normalizeArray(delivery.changedFiles).length > 0
    ? delivery.changedFiles
    : normalizeArray(state.traceability && state.traceability.iterations)
      .flatMap((item) => normalizeArray(item.filesChanged));
  const generatedAt = new Date().toISOString();

  if (languageCode(language) === "en") {
    return {
      "api.md": [
        "# API",
        "",
        text.generated,
        "",
        "## Scope",
        task.goal || text.noData,
        "",
        "## API Changes",
        bulletList(documentation.apiChanges, text.noApi),
        "",
        "## Related Requirements",
        bulletList(requirements.map((item) => `${item.id}: ${item.summary} (${item.status})`), text.noData),
      ].join("\n"),
      "changelog.md": [
        "# Changelog",
        "",
        text.generated,
        "",
        "## Entries",
        bulletList(documentation.changelogEntries, text.noChange),
        "",
        "## Changed Files",
        bulletList(changedFiles, text.noData),
        "",
        "## Validation",
        commandList(state, text.noValidation),
      ].join("\n"),
      "architecture.md": [
        "# System Architecture",
        "",
        text.generated,
        "",
        "## Architecture Notes",
        bulletList(documentation.architectureNotes, text.noArch),
        "",
        "## Decisions",
        bulletList((state.traceability && state.traceability.iterations || []).flatMap((item) => normalizeArray(item.decisions)), text.noData),
        "",
        "## Traceability",
        text.traceNotice,
        "",
        traceLines(state, text.noTrace),
      ].join("\n"),
      "implementation.md": [
        "# Implementation Notes",
        "",
        text.generated,
        "",
        "## Core Implementation",
        bulletList(documentation.implementationNotes, text.noImpl),
        "",
        "## Delivery Evidence",
        bulletList([
          delivery.changes && `Changes: ${delivery.changes}`,
          delivery.validationSummary && `Validation: ${delivery.validationSummary}`,
          delivery.risks && `Risks: ${delivery.risks}`,
          delivery.unfinishedItems && `Unfinished: ${delivery.unfinishedItems}`,
        ].filter(Boolean), text.noData),
        "",
        "## Traceability",
        text.traceNotice,
        "",
        traceLines(state, text.noTrace),
        "",
        `Generated at: ${generatedAt}`,
      ].join("\n"),
    };
  }

  return {
    "api.md": [
      "# API 文档",
      "",
      text.generated,
      "",
      "## 范围",
      task.goal || text.noData,
      "",
      "## API 变化",
      bulletList(documentation.apiChanges, text.noApi),
      "",
      "## 关联需求",
      bulletList(requirements.map((item) => `${item.id}: ${item.summary} (${item.status})`), text.noData),
    ].join("\n"),
    "changelog.md": [
      "# 变更日志",
      "",
      text.generated,
      "",
      "## 变更项",
      bulletList(documentation.changelogEntries, text.noChange),
      "",
      "## 变更文件",
      bulletList(changedFiles, text.noData),
      "",
      "## 验证",
      commandList(state, text.noValidation),
    ].join("\n"),
    "architecture.md": [
      "# 系统架构",
      "",
      text.generated,
      "",
      "## 架构说明",
      bulletList(documentation.architectureNotes, text.noArch),
      "",
      "## 决策记录",
      bulletList((state.traceability && state.traceability.iterations || []).flatMap((item) => normalizeArray(item.decisions)), text.noData),
      "",
      "## 可追溯记录",
      text.traceNotice,
      "",
      traceLines(state, text.noTrace),
    ].join("\n"),
    "implementation.md": [
      "# 核心功能实现说明",
      "",
      text.generated,
      "",
      "## 核心实现",
      bulletList(documentation.implementationNotes, text.noImpl),
      "",
      "## 交付证据",
      bulletList([
        delivery.changes && `变更：${delivery.changes}`,
        delivery.validationSummary && `验证：${delivery.validationSummary}`,
        delivery.risks && `风险：${delivery.risks}`,
        delivery.unfinishedItems && `未完成项：${delivery.unfinishedItems}`,
      ].filter(Boolean), text.noData),
      "",
      "## 可追溯记录",
      text.traceNotice,
      "",
      traceLines(state, text.noTrace),
      "",
      `生成时间：${generatedAt}`,
    ].join("\n"),
  };
}

async function generateDeliveryDocs(options) {
  const state = options.state;
  const sessionDir = options.sessionDir || path.dirname(options.stateJsonPath);
  const docsDir = path.join(sessionDir, "docs");
  const docs = buildDocs(state);
  await fs.promises.mkdir(docsDir, { recursive: true });
  for (const [fileName, content] of Object.entries(docs)) {
    await fs.promises.writeFile(path.join(docsDir, fileName), `${content.trimEnd()}\n`, "utf8");
  }
  const files = Object.keys(docs).map((fileName) => `.agent-state/auto-iterate/${state.session.session}/docs/${fileName}`);
  return {
    status: "generated",
    path: `.agent-state/auto-iterate/${state.session.session}/docs`,
    files,
    generatedAt: new Date().toISOString(),
  };
}

module.exports = {
  buildDocs,
  generateDeliveryDocs,
};
