// Re-export all pipeline types — split by domain.

export type {
  AutoIterateMode,
  WorkerResultStatus,
  RequirementStatus,
  ValidationStatus,
  PostChangeStatus,
  StopReason,
  WatchdogAction,
  WriteGuardIssueReason,
  LanguageCode,
  FlagStage,
  FlagKind,
} from "./core";

export type {
  FlagInfo,
  FlagIssue,
  FlagValidationResult,
  LanguageInfo,
  LanguageAnswersLike,
  ProgressOptions,
  StateValidationIssue,
  PipelineMarkdownIssue,
} from "./core";

export type {
  PipelineFocus,
  RequirementItem,
  WorkerRequirementPatch,
  PipelineBudgets,
  PipelineStateLike,
  PickFocusStateLike,
  DiagnoseStateLike,
  HypothesisItem,
  MetricValue,
  MetricComparisonItem,
  MetricComparisonResult,
  StatePersistenceOptions,
} from "./models";

export type {
  ValidationCommandResult,
  DeterministicValidationCommand,
  ValidationCommandConfig,
  ValidationHistoryEntry,
  ValidationPerCommandItem,
  ValidationResult,
  EffectiveValidationResult,
  PipelineValidationOptions,
  PipelineFailureInput,
  PipelineFailurePersistResult,
  IsolatedWorktreeOperationResult,
  IsolatedWorktreeApplyResult,
  DeliveryGateResult,
  MergeIterationContext,
  MergeIterationResult,
  MergeRequirementsContext,
  StatePatchResult,
  BudgetProgressContext,
  ApplyIterationProjectionInput,
  WriteGuardIssue,
  WriteGuardContext,
  WriteGuardReport,
  WriteGuardResult,
  ShouldStopContext,
  ShouldStopResult,
  PhaseGateContext,
  PhaseGateResult,
  LoopPolicyOptions,
  LoopPolicyResult,
  WatchdogContext,
  WatchdogResult,
  ProgressPayload,
  EmittedProgressPayload,
  IterationPaths,
  WorkerDecisionRequest,
  WorkerIterationResult,
  ParsedIterationResult,
  ValidParsedIterationResult,
  DeliveryDocsOptions,
  DeliveryDocsResult,
  BuildIterationPromptContext,
} from "./operations";